### ISSUE TITLE
Feature request: benchmarks with DOM access

### ISSUE THREAD

**Issue by pardahlman** [tjoskar/rust-wasm#1]
Many front end applications will interact with the DOM. I'm under the impression that DOM access is one of the slowest things you can do in a browser. It would be interesting to see benchmarks that compare wasm and js with DOM manipulation :wink:

**Comment by tjoskar** [comment]
Hi @pardahlman 👋

Correct me if I'm wrong but the reason why DOM access/manipulation is slow is not because of the JS engine but rather of the web api, and the fact that rendering is hard 😉(the reason why eg. React is faster than AngularJS (old angular) is because React is more clever when it comes to updates, and only updates the part that has changed).

Besides that, WebAssembly can currently not access DOM/WebAPI directly. WebAssembly can only communicate with js which can talk to the web api, so in order to access the DOM from WebAssembly we need to add some extra overhead. 

There is however a proposal to allow WebAssembly to call Web APIs directly 🎉But from my understanding, WebAssembly first need to have a garbage collector (https://github.com/WebAssembly/gc/blob/master/proposals/gc/Overview.md)

Having said that, there is this cool libary: https://github.com/koute/stdweb which creates a brige between Rust and the WebApi with some JS between and it should be fun to see how mutch overhead it adds.

**Comment by pardahlman** [comment]
A-ha, understood 👌 Then I guess that the performance gained from WebAssembly in for a _typical_ client app is marginal, as it would still rely on the slow DOM rendering.

It will be interesting to see where this will take us, especially considering web technology in client applications (a la Electron and other). It feels like one/the end game here is to have web based client apps with native performance on all major platform.
